FROM golang:1.10.3 as builder

# install kubebuilder (required for tests)
RUN wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.7/kubebuilder_1.0.7_linux_amd64.tar.gz \
	&& tar xvzf kubebuilder_1.0.7_linux_amd64.tar.gz \
	&& mkdir -p /usr/local \
	&& mv kubebuilder_1.0.7_linux_amd64 /usr/local/kubebuilder
ENV PATH="${PATH}:/usr/local/kubebuilder/bin"

# Copy in the go src
WORKDIR /go/src/github.com/alphagov/verify-metadata-controller
COPY . .

# run unit tests
ENV KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=1m
ENV KUBEBUILDER_CONTROLPLANE_STOP_TIMEOUT=1m
RUN go test -v ./...

